operand2:
  neg
creation_did:
  47
custom:
  email: chirag.lodaya@zebra.com
  exp_title: Exp_4


hydra:
    mode: MULTIRUN
    sweep:
      dir: /dbfs/mnt/qa1datamartstdsandbox/qa1datamartstdsandbox-ds-store-std-sandbox-rw/ML_Ops_Exp/${custom.email}/multirun/${now:%Y-%m-%d}/${custom.exp_title}
      subdir: ${hydra.job.override_dirname}
    sweeper:
        params:
          +operand1: add,sub
  
