creation_did:
  47
custom:
  email: chirag.lodaya@zebra.com
  exp_title: Exp_3
learning_rate:
  0.01


hydra:
    mode: MULTIRUN
    sweep:
      dir: /dbfs/mnt/qa1datamartstdsandbox/qa1datamartstdsandbox-ds-store-std-sandbox-rw/ML_Ops_Exp/${custom.email}/${now:%Y-%m-%d}/${custom.exp_title}
      subdir: ${hydra.job.override_dirname}
    sweeper:
        params:
          +prev_sweep: Def
          +batch_size: 64,128
          