operand1:
  add
operand2:
  neg
batch_size:
  64
creation_did: 
  47
custom:
  email: chirag.lodaya@zebra.com
  exp_title: Exp_2

hydra:
    run:
      dir: /dbfs/mnt/qa1datamartstdsandbox/qa1datamartstdsandbox-ds-store-std-sandbox-rw/ML_Ops_Exp/${custom.email}/singlerun/${now:%Y-%m-%d}/${custom.exp_title}