experiment_name:
  "10-08-2023_t2"

network:
    inputs: 2
    outputs: 3
    layer_size: 60
    nr_layers: 8

optimiser:
    lr: 1e-3
    scheduler: exponential_lr
    iter: 5000
    
hydra:
    mode: MULTIRUN
    sweep:
      dir: /dbfs/FileStore/MLO_Test_Temp/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
      subdir: ${hydra.job.num}
    sweeper:
        params:
          +n: 20,30
          +prev_sweep: "+operand1_add" , "+operand1_sub"
    